import type { Metadata } from "next";
import "./globals.css";
import "./globals.css";
import NavBar from "@/components/common/navbar";
import { Poppins } from "next/font/google";
import Footer from "@/components/common/footer";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased `}>
        <NavBar />
        <ToastContainer />
        {children}
        <Footer />
      </body>
    </html>
  );
}
